### ISSUE TITLE
How to add breadcrumbs for a dynamic url

### ISSUE THREAD

**Issue by kasuboski** [coreui/coreui-free-react-admin-template#27]
How do you add a breadcrumb for a url like /resource/:id

**Comment by tfitzhugh** [comment]
I am wondering the same thing as kasuboski. Is there a way to have a dynamic URL value display as a breadcrumb?

**Comment by adcuz** [comment]
This is a bit rough and not thoroughly tested, but I have updated the Breadcrumb component to achieve this. There's a function that matches the current URL with the routes list with an exact match, this will attempt to match wildcard routes:

````
const findRouteName = (url) => {
  if (routes[url]) {
    return routes[url];
  }

  const matchedWildcardRoute = Object.keys(routes).find((route) => {
    const routeSegments = route.split('/');
    const urlSegments = url.split('/');

    if (routeSegments.length !== urlSegments.length) {
      return false;
    }

    routeSegments.map((seg, index) => {
      if (seg.startsWith(':')) {
        urlSegments[index] = seg;
      }
    });

    return routes[urlSegments.join('/')] || false;
  });

  return routes[matchedWildcardRoute];
};
````

**Comment by gorjan-mishevski** [comment]
Ahh just hit the same problem. Would be nice if they can implement it. I think this is very important feature to have

**Comment by jovanxua** [comment]
Any workaround for this issue ? Agree that this is an important feature common to many web apps.

**Comment by xidedix** [comment]
Hi, 
please verify the following solution:   

**CoreUI v2**: update `dependencies` in `package.json`
````js
"@coreui/react": "^2.0.4",
````
---  
**CoreUI v1**: update `Breadcrumb` component to current version `v1.0.11` commit https://github.com/coreui/coreui-free-react-admin-template/pull/94/commits/cf816043b4f6d786529efb1a7f0ad41cce144906

https://github.com/coreui/coreui-free-react-admin-template/blob/v1/React_Full_Project/src/components/Breadcrumb/Breadcrumb.js

**Comment by afgallo** [comment]
Hi, I know I'm late to the party, but this does not seem to work in version 3.x?

**Comment by woothu** [comment]
@afgallo yes these are resolved issues concerning that:

https://github.com/coreui/coreui-react/issues/136
https://github.com/coreui/coreui-react/issues/118

**Comment by afgallo** [comment]
Hi @woothu thanks for referencing the issues above and for your work on this template, it's pretty damn good!
I can see this issue seems to be fixed by the comments on the above threads, however, it still doesn't show in my breadcrumbs. Here's what I have configured (I'd appreciate if you had time to take a look):

`
const routes = [
  { path: '/', exact: true, name: 'Home' },
  { path: '/dashboard', name: 'Dashboard', component: DashboardPage },
  { path: '/companies/:companyName', name: 'Companies', component: CompanyPage, exact: true },
  { path: '/companies/:companyName/details', name: 'Detailed View', component: CompanyDetailsPage, exact: true },
]
`

Screenshot of what gets displayed in Breadcrumbs:

![image](https://user-images.githubusercontent.com/9999415/91704983-aa7fbb00-ebbf-11ea-8482-3b4700ee1bd3.png)

**Comment by afgallo** [comment]
Hi @woothu,

I was just wondering if my implementation above is wrong or if my use case can be supported?

Thanks for your time.

**Comment by linh626688** [comment]
@woothu do you have any solution for v3.2.2 with `CBreadcrumbRouter` ?

**Comment by luthfi28** [comment]
Delete all the code in the **AppBreadcrumb.js** file and paste the following code 

```js
import React from "react";
import { useLocation } from "react-router-dom";

import routes from "../routes";

import { CBreadcrumb, CBreadcrumbItem } from "@coreui/react";

const AppBreadcrumb = () => {
  const locations = useLocation().pathname.split("/");

  return (
    <CBreadcrumb className="m-0 ms-2">
      <CBreadcrumbItem href="/">Home</CBreadcrumbItem>
      {locations.map((item, key) => {
        if (key == locations.length - 1)
          return item ? <CBreadcrumbItem active>{item}</CBreadcrumbItem> : "";
        return item ? <CBreadcrumbItem href="/">{item}</CBreadcrumbItem> : "";
      })}
    </CBreadcrumb>
  );
};

export default React.memo(AppBreadcrumb);

```

**Comment by pnaa** [comment]
AppBreadcrumb.js shows empty if path is from a dynamic :id 
If for some reason path doesn't exist in router.js, it will bypass the segment.

just cleared with the following code:
```

import { matchPath } from 'react-router-dom';

  const getRouteName = (pathname, routes) => {
    for (var i = 0; i < routes.length; i++) {
      var routePath = routes[i];
      if (matchPath(pathname, { path: routePath.path, exact: true, strict: false })) {
        return routePath.name;
      }
    }
    return null;
  };

  const getBreadcrumbs = (location) => {
    const breadcrumbs = [];
    location.split('/').reduce((prev, curr, index, array) => {
      const currentPathname = `${prev}/${curr}`;
      const routeName = getRouteName(currentPathname, routes);
      if (routeName) {
        breadcrumbs.push({
          pathname: currentPathname,
          name: routeName,
          active: index + 1 === array.length ? true : false,
        });
      }
      return currentPathname;
    });
    return breadcrumbs;
  };
```
